# -*- coding: utf-8 -*-
"""football.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z191Ts3p2Er3sJHZpVs6O7zbs0HK7HqW
"""

!pip install plotly

import plotly.graph_objects as go
import numpy as np

# Function to generate a football shape
def generate_football():
    u = np.linspace(0, 2 * np.pi, 100)
    v = np.linspace(0, np.pi, 50)

    x = 0.5 * np.outer(np.cos(u), np.sin(v))
    y = 0.5 * np.outer(np.sin(u), np.sin(v))
    z = 0.5 * np.outer(np.ones(np.size(u)), np.cos(v))

    return x, y, z

# Generate football coordinates
football_x, football_y, football_z = generate_football()

# Create a 3D scatter plot
fig = go.Figure(data=[go.Surface(x=football_x, y=football_y, z=football_z)])

# Update layout to set 3D aspect and add rotation capabilities
fig.update_layout(
    scene=dict(
        aspectmode="data",
        camera=dict(up=dict(x=0, y=0, z=1), center=dict(x=0, y=0, z=0), eye=dict(x=2.5, y=0, z=0)),
        dragmode="turntable",  # Enables rotation
    )
)

# Show the plot
fig.show()

